USE TechShop;

--Find Customers Who Have Not Placed Any Orders
SELECT FirstName, LastName 
FROM Customers 
WHERE CustomerID NOT IN (
    SELECT DISTINCT CustomerID FROM Orders
);

--Find the Total Number of Products Available for Sale
SELECT (SELECT COUNT(*) FROM Products) AS TotalProducts;

-- Calculate the Total Revenue Generated by TechShop
SELECT (SELECT SUM(TotalAmount) FROM Orders) AS TotalRevenue;

--Average Quantity Ordered for Products in a Specific Category
DECLARE @CategoryName NVARCHAR(100);

ALTER TABLE Products ADD Category NVARCHAR(100);

UPDATE Products 
SET Category = 'Electronics' 
WHERE ProductName IN ('Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Camera');

DECLARE @CategoryName NVARCHAR(100) = 'Electronics';

SELECT AVG(od.Quantity) AS AverageQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
WHERE p.Category = @CategoryName;

--Total Revenue Generated by a Specific Customer
DECLARE @CustomerID INT;
SET @CustomerID = 1;

SELECT (
    SELECT SUM(TotalAmount) 
    FROM Orders 
    WHERE CustomerID = @CustomerID
) AS TotalRevenueByCustomer;

--Find Customers Who Have Placed the Most Orders
SELECT FirstName, LastName, OrderCount
FROM (
    SELECT c.FirstName, c.LastName, COUNT(o.OrderID) AS OrderCount
    FROM Customers c
    LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
    GROUP BY c.CustomerID, c.FirstName, c.LastName
) AS OrderCounts
WHERE OrderCount = (SELECT MAX(OrderCount) FROM (SELECT COUNT(OrderID) AS OrderCount FROM Orders GROUP BY CustomerID) AS MaxOrders);

--Find the Most Popular Product Category (Highest Ordered Quantity)
SELECT Category, TotalOrderedQuantity
FROM (
    SELECT p.Category, SUM(od.Quantity) AS TotalOrderedQuantity
    FROM OrderDetails od
    JOIN Products p ON od.ProductID = p.ProductID
    GROUP BY p.Category
) AS CategoryOrders
WHERE TotalOrderedQuantity = (SELECT MAX(TotalOrderedQuantity) FROM (SELECT SUM(Quantity) AS TotalOrderedQuantity FROM OrderDetails od JOIN Products p ON od.ProductID = p.ProductID GROUP BY p.Category) AS MaxCategory);

--Find the Customer Who Has Spent the Most on Electronic Gadgets
SELECT FirstName, LastName, TotalSpent
FROM (
    SELECT c.FirstName, c.LastName, SUM(od.Quantity * p.Price) AS TotalSpent
    FROM Customers c
    JOIN Orders o ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    JOIN Products p ON od.ProductID = p.ProductID
    WHERE p.Category = 'Electronics'
    GROUP BY c.CustomerID, c.FirstName, c.LastName
) AS CustomerSpending
WHERE TotalSpent = (SELECT MAX(TotalSpent) FROM (SELECT SUM(od.Quantity * p.Price) AS TotalSpent FROM Orders o JOIN OrderDetails od ON o.OrderID = od.OrderID JOIN Products p ON od.ProductID = p.ProductID WHERE p.Category = 'Electronics' GROUP BY o.CustomerID) AS MaxSpender);

-- Calculate the Average Order Value (Total Revenue / Number of Orders)
SELECT (SELECT SUM(TotalAmount) FROM Orders) / (SELECT COUNT(*) FROM Orders) AS AverageOrderValue;

--Find the Total Number of Orders Placed by Each Customer
SELECT FirstName, LastName, 
    (SELECT COUNT(*) FROM Orders o WHERE o.CustomerID = c.CustomerID) AS TotalOrders
FROM Customers c;

