USE TechShop;

--Retrieve a list of all orders along with customer information
SELECT o.OrderID, c.FirstName, c.LastName, c.Email, c.Phone, 
       o.OrderDate, o.TotalAmount
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
ORDER BY o.OrderDate DESC;

-- The total revenue generated by each product
SELECT p.ProductName, SUM(od.Quantity * p.Price) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalRevenue DESC;

-- List all customers who have made at least one purchase
SELECT DISTINCT c.CustomerID, c.FirstName, c.LastName, c.Email, c.Phone, c.Address
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID;

--The most popular electronic gadget (highest total quantity ordered)
SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalQuantityOrdered DESC;

-- Retrieving a list of electronic gadgets along with their categories
SELECT ProductName, Description  
FROM Products  
WHERE ProductName IN ('Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smartwatch', 'Camera', 'Printer', 'Keyboard', 'Mouse', 'External Hard Drive');

--Calculate the average order value for each customer
SELECT c.FirstName, c.LastName, AVG(o.TotalAmount) AS AverageOrderValue
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY AverageOrderValue DESC;

--Find the order with the highest total revenue
SELECT TOP 1  o.OrderID, c.FirstName, c.LastName, o.TotalAmount 
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
ORDER BY o.TotalAmount DESC;

--List electronic gadgets and the number of times each product has been ordered
SELECT p.ProductName, COUNT(od.OrderID) AS NumberOfTimesOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY NumberOfTimesOrdered DESC;

--Find customers who have purchased a specific electronic gadget (input required)
SELECT DISTINCT c.FirstName, c.LastName, c.Email, c.Phone
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
WHERE p.ProductName = 'Laptop';  

--Calculate total revenue generated within a specific time period (input required)
SELECT SUM(o.TotalAmount) AS TotalRevenue
FROM Orders o
WHERE o.OrderDate BETWEEN '2025-03-01' AND '2025-03-20'; 




